Ensure Helm dependencies are correctly frozen
- Use "helm repo add" and "helm dependency build" instead of "helm
  dependency update" before Megalinter run, and move from a Megalinter
  pre-lint command to the GitHub Actions pipeline.

- Change a couple of our subcharts to use OCI repos to ensure the logic
  handles them correctly.

- Update packaging to linuxfoundation/lfx-public-workflows#7 to ensure
  packaging doesn't make changes to the lockfile either.

Signed-off-by: Eric Searcy <eric@linuxfoundation.org>

diff --git a/.github/workflows/mega-linter.yml b/.github/workflows/mega-linter.yml
--- a/.github/workflows/mega-linter.yml
+++ b/.github/workflows/mega-linter.yml
@@ -29,6 +29,21 @@ jobs:
         with:
           fetch-depth: 0
 
+      # Installs packaged subcharts under charts/${chart}/charts/*.tgz. Also
+      # fails if the Chart.lock digest is wrong. Does not support multiple
+      # charts: `charts/*` is expected to resolve to a single path.
+      - name: Helm dependency fetch
+        shell: bash
+        run: |
+          set -euo pipefail
+          for chart in charts/*; do
+            if [ -f "${chart}/Chart.lock" ]; then
+              yq -r '.dependencies[] | select(.repository | contains("oci://") == false) | "\(.name) \(.repository)"' \
+                "${chart}/Chart.yaml" | xargs -L1 helm repo add
+              helm dependency build "${chart}"
+            fi
+          done
+
       # MegaLinter
       - name: MegaLinter
         id: ml
